ttricco/sarracen

sarracen/sarracen_dataframe.py
Includes `_params` & `params` in the metadata of `SarracenDataFrame.py`, to avoid a `UserWarning` thrown by pandas.
=> Add _params & params as properties of SarracenDataFrame.py

sarracen/interpolate.py, sarracen/kernels.py, sarracen/tests/test_interpolate.py
Introduces the `interpolate2D` function, which maps particle data to a 2D grid of pixels. The data from a `SarracenDataFrame` along two axes is plotted with a user-defined smoothing kernel.
Example of a plot created using the `interpolate2D` function:
```
image = interpolate2D(df, 'rx', 'ry', 'P', CubicSplineKernel(), 0, 0, 0.015624, 0.015624, 64, 128)
fig, ax = plt.subplots(figsize=(3, 4))
img = ax.imshow(image, cmap='RdBu', origin='lower', vmin=0.985, vmax=1.015, extent=[0, 1, 0, 2])
ax.set_xlabel('rx')
ax.set_ylabel('ry')
fig.colorbar(img, ax=ax, label='P')
plt.show()
```
=> Implementation of 2D Interpolation

sarracen/interpolate.py, sarracen/render.py, sarracen/sarracen_dataframe.py, sarracen/tests/test_render.py, sarracen/tests/test_sarracen_dataframe.py
Creates a function in `SarracenDataFrame` `render(target)`, which produces and returns a matplotlib figure & axes containing a 2D interpolated plot of the provided variable. The directional axes, bounds of the plot, kernel, and resolution are determined automatically, or can be manually tuned by the user.
By default, arguments are selected by the following rules:
- x & y: First look for the keywords 'x' and 'y' or 'rx' and 'ry' in the columns. If these are not found, fallback to the first two columns.
- kernel: A CubicSplineKernel is chosen by default.
- xmin, ymin, xmax, ymax: These are set to the minimum and maximum values of x and y in the dataframe, and then snapped to the nearest integer if they are between 1e-4 of an integer.
- pixcountx & pixcounty: pixcountx is set to a default …
=> 2D Interpolation plotting

sarracen/__init__.py, sarracen/interpolate.py, sarracen/kernels/base_kernel.py, sarracen/kernels/cubic_spline.py, sarracen/kernels/quartic_spline.py, sarracen/kernels/quintic_spline.py, sarracen/tests/test_interpolate.py
Adds a new interpolation function `interpolate2DCross` to `interpolate.py`, which enables interpolation of 2D data inside a `SarracenDataFrame` over a one dimensional line.
Sample:
```
output = interpolate2DCross(df, 'x', 'y', 'colour', QuinticSplineKernel(2), 0.4, 0, 0.6, 2, 500)
fig, ax = plt.subplots()
sns.lineplot(x=np.linspace(0, np.sqrt(2**2 + 0.4**2), 500), y=output, ax=ax)
plt.show()
```
New unit tests in `test_interpolate.py` have been included for this functionality.
=> 1D Cross-Sections over 2D Data

sarracen/sarracen_dataframe.py, sarracen/tests/test_sarracen_dataframe.py
Includes functionality in SarracenDataFrame to detect 3-dimensional data vs 2-dimensional data. As well, helper methods for Phantom data are included to derive values for mass and density.
Test cases have been included to test dimensionality detection.
=> Extend SarracenDataFrame to accept 3-dimensional data

sarracen/interpolate.py
Adjust 2D rendering to include some optimizations for memory and performance, similar to the optimizations used in 1D cross sections:
- Instead of creating copies of necessary data, use Boolean filters to save memory.
- Vectorize the calculation of contributions to individual pixels, increasing performance with higher pixel counts.
=> Performance and memory optimizations for 2D rendering

sarracen/__init__.py, sarracen/interpolate.py, sarracen/tests/test_interpolate.py
Adds a new interpolation function `interpolate3DCross`, to interpolate 3D data contained in a `SarracenDataFrame` over a 2-dimensional grid. The cross-section is taken over a specified value of z.
Sample:
New unit tests have been added to test this functionality.
=> 2D Cross-Sections over 3D Data

sarracen/interpolate.py, sarracen/kernels/base_kernel.py, sarracen/render.py, sarracen/sarracen_dataframe.py, sarracen/tests/test_interpolate.py, sarracen/tests/test_kernels.py, sarracen/tests/test_render.py
Adds a new interpolation function `interpolate3DCross`, which interpolates a target variable in a 3-dimensional SarracenDataFrame to a 2D grid, by interpolating along columns in the z-direction.
In addition to the 3D column interpolation function, a new render function `render_3d` has been added to both SarracenDataFrame and `render.py`, which produces a matplotlib figure containing an image/colorbar with information obtained from `interpolate3DCross`.
Sample:
Test cases have been included for both the 3D column interpolation & render functions.
A hotfix for the 3D -> 1D cross section unit test has also been included.
=> 3D Column Rendering

sarracen/interpolate.py, sarracen/tests/test_interpolate.py
Includes new sections on unit tests for all four currently available interpolation processes (2D Rendering, 3D Column Rendering, 3D->2D cross-sections, and 2D->1D cross-sections). These new tests provide greater coverage of the interpolation functions, including:
- Different Kernels
- Smoothing lengths, density, target, and mass values different than one
- Non-square interpolation grids (different sizes & pixel widths)
Some additional cases that are not included in this PR, but should be included in the future:
- Particle(s) outside of the interpolation grid
- Interpolation of several particles
- Particles with zero weight
- Particles of different types
=> Additional unit tests for interpolation functions

sarracen/interpolate.py, sarracen/render.py, sarracen/sarracen_dataframe.py, sarracen/tests/test_render.py
Add a new rendering function `render_3d_cross`, to both `render.py` and `SarracenDataFrame`. This function returns a matplotlib figure & axes containing a 3d->2d cross-sectional plot of a 3d particle dataset.
Sample of a 3d->2d cross-sectional plot:
Documentation and unit tests are also included for this new function.
=> Add render function for 3D->2D cross-sections

sarracen/interpolate.py, sarracen/kernels/base_kernel.py
Switch out the use of scipy's `quad` function in favour of `np.trapz` for calculating the 2D interpolated form of the 3D kernel for 3D column integration. As well, the default 1000 sample kernel is cached upon calculation.
This change has the greatest effect on interpolating datasets with low numbers of particles, with a 2x speedup observed on low-particle datasets.
=> Use trapezoid rule for calculating 3D column kernels

sarracen/interpolate.py, sarracen/kernels/base_kernel.py, sarracen/render.py, sarracen/sarracen_dataframe.py, sarracen/tests/test_render.py
Adds new arguments to the sarracen render API, which allows passing of custom arguments to underlying matplotlib & seaborn functions. The resulting plots can now be customized to a much deeper degree. As well, the render functions can now be passed a user-defined axes object, allowing for the creation of larger plots and multiplots.
Internally, the codebase for interpolation and rendering has been refactored to share common code. Three of the four interpolation functions now use a single internal numba function, which will simplify further updates.
=> Additional arguments and refactoring of interpolation & render functions.

sarracen/interpolate.py, sarracen/render.py, sarracen/sarracen_dataframe.py, sarracen/tests/test_interpolate.py, sarracen/tests/test_render.py
Introduces three new interpolation / render functions for visualizing vector data:
- 2D rendering of vector data in a 2D particle system.
- 3D column interpolation of vector data in a 3D particle system.
- 3D cross-sections of vector data in a 3D particle system.
Interpolated vector fields can be plotted in two ways. A streamline plot with `ax.streamplot`, or a vector field with arrows using `ax.quiver`.
An example of the two different plotting methods:
Streamlines are on the left, arrows are on the right. cmap is set to 'hot'.
=> Interpolated plotting of vector quantities

sarracen/sarracen_dataframe.py
Adds an `_constructor` private method to SarracenDataFrame. This ensures that when a SarracenDataFrame is sliced or manipulated in a way that doesn't return a Series, a SarracenDataFrame is returned instead.
With this fix, particle data can now be manipulated by the user before plotting, without losing any vital information.
=> SarracenDataFrame slicing bugfix

sarracen/interpolate.py, sarracen/kernels/base_kernel.py, sarracen/kernels/cubic_spline.py, sarracen/kernels/quartic_spline.py, sarracen/kernels/quintic_spline.py, sarracen/render.py, sarracen/sarracen_dataframe.py, sarracen/tests/test_interpolate.py, sarracen/tests/test_kernels.py, sarracen/tests/test_render.py, sarracen/tests/test_sarracen_dataframe.py
Rewrite of the unit tests for interpolation functions, render functions, and kernels. The total number of unit tests has been greatly expanded, from 22 to 73. The depth of testing has been greatly expanded, to include in-depth tests of rotations, vector functions, and more. As well, all interpolation and rendering tests are performed on both CPU and GPU backends (the GPU tests will only run if a CUDA supported device is detected).
In this new suite, a few of the tests are currently expected to fail, and highlight issues that should be fixed in the future:
- `test_single_repeated_particle` will fail on the CPU backend, highlighting a race condition in the CPU interpolation functions.
- Some other tests involving interpolation of two particles (`test_axes_rotation_equivalency` for example) …
=> Advanced unit test suite

sarracen/interpolate/base_backend.py, sarracen/interpolate/cpu_backend.py, sarracen/interpolate/gpu_backend.py, sarracen/interpolate/interpolate.py, sarracen/kernels/cubic_spline_exact.py, sarracen/render.py, sarracen/sarracen_dataframe.py, sarracen/tests/test_interpolate.py
Implements exact SPH interpolation using an analytic solution for volume & surface integrals for the cubic spline kernels, with a similar implementation to Splash, by Maya Petkova and Daniel Price.
This type of interpolation can be performed for 2D scalar and vector interpolation, and for 3D scalar and vector projective interpolation. There is currently no support for 2D or 3D cross-sections.
Example:
=> Exact 2D & 3D projective interpolation

sarracen/render.py, sarracen/sarracen_dataframe.py
Adds support for logarithmic scaling in the scalar rendering functions (`render_2d_cross`, `render_2d`, `render_3d_cross`, `render_3d`). For `render_2d_cross` the y-axis is scaled logarithmically, while the logarithmic scale is applied to the color scale for the other rendering methods.
Example:
=> Add support for logarithmic plotting

sarracen/render.py, sarracen/sarracen_dataframe.py
Add a key to `arrowplot` generated images, which displays the magnitude of the target vector that each arrow represents. The properties of this key can be altered with the arguments `qkey` and `qkey_kws`.
Example:
Generated with: (`sdf` contains vortex data)
```
fig, ax = plt.subplots(figsize=(9, 9))
sdf.render_2d('rho', x_pixels=1000, ax=ax, cmap='viridis')
sdf.arrowplot(('bx', 'by'), x_arrows=30, exact=True, ax=ax, qkey_kws={'X': 0.9, 'U': 0.05})
ax.set_title("Orszag-Tang Vortex with Magnetic Field")
plt.show()
```
=> Add support for arrowplot quiver keys

sarracen/interpolate/base_backend.py, sarracen/interpolate/cpu_backend.py, sarracen/interpolate/gpu_backend.py, sarracen/interpolate/interpolate.py, sarracen/readers/read_phantom.py, sarracen/sarracen_dataframe.py
Generalizes the way that sarracen rendering and interpolation functions work with mass and density data, to work seamlessly in more scenarios. As well, the `read_phantom` method has been extended with more options, to work better in more cases:
- `drop_sinks`: Sink particles can cause significant conflicts and memory issues when included in the DataFrame structure. When true, the sink particles are dropped from the dataset. This is true by default.
- `separate_types`: The existence of several particle types with different properties (such as masses) can cause confusion and issues with rendering & interpolation functions. When true, the different particle types are separated into different DataFrames (in this case, read_phantom returns a list of dataframes). This is true by default.
When …
=> Proper handling of SPH mass and density data

sarracen/__init__.py, sarracen/interpolate/__init__.py, sarracen/interpolate/base_backend.py, sarracen/interpolate/cpu_backend.py, sarracen/interpolate/gpu_backend.py, sarracen/interpolate/interpolate.py, sarracen/render.py, sarracen/sarracen_dataframe.py, sarracen/tests/test_interpolate.py, sarracen/tests/test_render.py, sarracen/tests/test_sarracen_dataframe.py
Previously, scalar rendering was split into four different functions (`render_2d`, `render_2d_cross`, `render_3d`, `render_3d_cross`). The user would have to pick which one to choose based off the type of dataset they were using, and whether they want to perform a cross-section or not. These four functions have been merged into one function (`render`) for ease of use. The specific kind of interpolation and rendering used depends on the arguments and the type of data supplied to the function.
Now, the user has access to three different rendering functions overall: `render`, `streamlines`, and `arrowplot`.
=> Merge scalar rendering functions into one function

sarracen/interpolate/__init__.py, sarracen/interpolate/base_backend.py, sarracen/interpolate/cpu_backend.py, sarracen/interpolate/gpu_backend.py, sarracen/interpolate/interpolate.py, sarracen/readers/read_phantom.py, sarracen/sarracen_dataframe.py, sarracen/tests/test_interpolate.py
Creates a new interpolation function`interpolate_3d_grid`, which takes a 3D `SarracenDataFrame` and returns an interpolated 3D grid with the specified number of 3D pixels. This function does not have a corresponding rendering function, unlike every other interpolation function prior to this point.
As well, an `sdf.sph_interpolate()` method has been included, which interpolates data within a `SarracenDataFrame` to either a 2D or 3D grid, depending on the number of dimensions within the data. The method is named `sph_interpolate` and not just `interpolate` to avoid conflict the existing `DataFrame.interpolate()` method within pandas.
=> Interpolation of 3D data to a 3D grid

sarracen/interpolate/__init__.py, sarracen/interpolate/base_backend.py, sarracen/interpolate/cpu_backend.py, sarracen/interpolate/gpu_backend.py, sarracen/interpolate/interpolate.py, sarracen/readers/read_phantom.py, sarracen/render.py, sarracen/sarracen_dataframe.py, sarracen/tests/test_interpolate.py
Adds a new interpolation / rendering function `render_3d_line`, which takes an SPH cross-sectional line defined by two coordinates in data space. This is very similar to `render_2d_line`, except it is specifically designed to work in 3 dimensions. The two coordinates can be anywhere in 3D space (except they cannot both be in the same place).
Example (3D -> 2D cross section on left, 3D -> 1D line interpolation on right from (-0.5, -0.5) to (0.5, 0.5)):
=> 3-Dimensional Line Interpolation

sarracen/sarracen_dataframe.py
Small fix to arguments supplied to `interpolate_2d` from `SarracenDataFrame`, resolving a runtime error.
=> Small fix for 2D interpolation from SarracenDataFrame

docs/index.rst, docs/installation.rst, docs/quick-start.rst
Expand the documentation to have installation instructions for the latest stable release via PyPi, and the latest development snapshots from GitHub with information on how to manually handle dependencies.
=> Expand installation documentation

docs/api.rst, sarracen/sarracen_dataframe.py
Include examples on how to build a SarracenDataFrame without file reading, such as from a Python dictionary or NumPy array. 
Include information on params dictionary, notably the mass key for uniform, constant mass particles. 
Include specific mention of required columns for interpolation and rendering.
=> Expand documentation for SarracenDataFrame construction

sarracen/interpolate/cpu_backend.py, sarracen/interpolate/gpu_backend.py, sarracen/tests/test_interpolate.py
Fixes cases for exact rendering where pixels on the edge of a particle's smoothing circle were incorrectly cut.
As an example, here is a single particle drawn at a low resolution for both exact & fast rendering with this change applied:
Before this fix, the exact and fast interpolations looked identical, with the outermost pixels not included in the exact interpolation.
This should resolve #49.
=> Pixel culling fix for exact interpolation

sarracen/interpolate/cpu_backend.py, sarracen/interpolate/interpolate.py, sarracen/render.py, sarracen/sarracen_dataframe.py, sarracen/tests/test_interpolate.py
Option added to render and interpolation to impose a minimum smoothing length based on the grid size. 
This addresses the problem of particles not contributing to any grid cell if their smoothing length is small enough. Guarantees particles will contribute to at least one grid cell.
The minimum smoothing length is chosen to be 0.5 * grid cell size (max between x/y if aspect ratio is not 1:1).
=> Minimum smoothing length based on grid size

sarracen/render.py
Allow custom colorbar custom label when rendering. Label of the colorbar is defined as previously if 'label' is not in the cbar_kws dictionnary.
=> Allow custom colorbar custom label

sarracen/readers/read_phantom.py
`read_phantom()` implicitly assumes that there are sink particles when `separate_types='all'`. This creates an (empty) SarracenDataFrame for the sink particles, which is unnecessary.
=> Bug fix when separate_types='all' but there are no sink particles

sarracen/interpolate/interpolate.py, sarracen/render.py, sarracen/tests/test_render.py
Remove _snap, which previously rounded x/y limits when they were within 1e-4 of an integer value. 
If the min/max limits were both within 1e-4 of the same integer, then they would round to the same value. This means the width would be 0, causing several issues, such as divide by zero errors.
Fixes #66.
=> Snap removal

sarracen/readers/read_phantom.py, sarracen/sarracen_dataframe.py, sarracen/tests/readers/test_read_phantom.py
`read_phantom()` creates a `mass` key in `params` to store the global mass of a particle, thereby avoiding storage of duplicated mass values per particle. This doesn't work when a dataframe contains more than 1 species of particles that have different particle masses (e.g., gas + dust).
This PR fixes/changes a few things:
- `read_phantom()` will create a `mass` column if more than 1 particle species is present (multiple `itype`). If there is a single particle species, such as gas only, then it relies on the global variable `mass` in `params` instead, as it has done before. This should fix issue #62.
- `read_phantom()` has reliable detection of 32/64-bit precision for default ints and floats. Previously, this might fail to detect 64-bit ints.
- There are now unit tests of the phantom data …
=> Phantom data reads and multiple particle types

sarracen/sarracen_dataframe.py
overriding drop() and __getitem__() is unnecessary. Only needed to define _internal_names inside SarracenDataFrame and pandas handles everything automatically. This will re-detect special columns in the dataframe copy.
Closes #71.
=> avoid inheritance of special columns when copying dataframes

sarracen/__init__.py, sarracen/readers/read_gradsph.py
Add file reading for the GradSPH file format.
Works for the sample data file provided. Will need modifications for reading MHD or other particle attributes.
=> 79 file format for gradsph files

sarracen/interpolate/interpolate.py, sarracen/render.py
Additional optional argument to plot in a corotating frame. Takes in a list containing the x,y,z coordinates of two locations. Rotates all the particles accordingly.
Tested with splash outputs.
=> Adding option to plot in a corotating frame

sarracen/render.py, sarracen/sarracen_dataframe.py, sarracen/tests/test_render.py
I added the ability to do a symmetric log scale on rendering, which allows data with negative values to be put on log scale as well. A test was added and passed.
=> added symlognorm for render and tests

sarracen/readers/read_phantom.py
Changed read_phantom.py so that if it detects an apr_level array it adds a mass column and rescales the particle masses as appropriate.
Note that when we have APR+DUST this will need to be revised.
=> Added APR compatibility

sarracen/disc/surface_density.py
Fixed a bug where sarracen.disc.azimuthal_average took the sum of the target in a radial bin rather than its average.
=> Fixed bug in sarracen.disc.azimuthal_average

sarracen/readers/read_shamrock.py, sarracen/readers/read_shamrock_vtk.py
Hello!
We now have a native dump format for Shamrock (though the vtk format is also still used).
In this PR:
- the former reader is renamed with a _vtk
- the new reader is added.
I tested the reader on a dummy file with several patches, and a disc simulation file with 1 patch.
=> Add a reader for Shamrock native dump format

sarracen/sarracen_dataframe.py
Added the method classify_sink to the SarracenDataFrame, which calculates the total energy of each SPH particle relative to each sink particle in order to classify particles by which sink particle they are gravitationally bound to.
=> Classify particles by sink

sarracen/tests/test_render.py
Removing the unit test that checks if axes ticks are removed if the image is rotated as it is not required as of [PR #125](url)
=> Removing out-of-date unit test
